import { expect, test, type Page } from '@playwright/test'

async function windowActivation(page: Page, active: boolean) {
  await page.evaluate(active => window.dispatchEvent(new FocusEvent(active ? 'focus' : 'blur')), active)
  await expect(page.locator('html')).toHaveAttribute('data-window-active', String(active))
}

test('pointer actions stay quiet; keyboard focus hides while inactive and returns without moving focus', async ({ page }) => {
  await page.goto('/?demo')
  const add = page.locator('.toolbar').getByRole('button', { name: '添加令牌', exact: true })
  await add.click()
  const close = page.getByRole('button', { name: '关闭弹窗', exact: true })
  await expect(close).toBeFocused()
  await expect(close).toHaveCSS('outline-style', 'none')
  await page.keyboard.press('Tab')
  const tab = page.getByRole('tab', { name: '二维码 / 链接', exact: true })
  await expect(tab).toBeFocused()
  await expect(tab).toHaveCSS('outline-style', 'solid')
  await expect(tab).toHaveCSS('outline-width', '2px')
  await windowActivation(page, false)
  await expect(tab).toHaveCSS('outline-style', 'none')
  await expect(tab).toBeFocused()
  await windowActivation(page, true)
  await expect(tab).toHaveCSS('outline-style', 'solid')
  await expect(tab).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(add).toBeFocused()
  await expect(add).toHaveCSS('outline-style', 'solid')
  await add.click()
  await expect(close).toBeFocused()
  await expect(close).toHaveCSS('outline-style', 'none')
})

test('inactive editing removes only the focus halo and keeps the draft, caret and selected settings', async ({ page }) => {
  await page.goto('/?demo')
  await page.locator('.toolbar').getByRole('button', { name: '添加令牌', exact: true }).click()
  await page.getByRole('tab', { name: '手动输入', exact: true }).click()
  const issuer = page.getByPlaceholder('例如 Google、GitHub')
  await issuer.fill('Focus fixture')
  await issuer.evaluate((element: HTMLInputElement) => element.setSelectionRange(2, 5))
  await expect(issuer).toBeFocused()
  await expect(issuer).not.toHaveCSS('box-shadow', 'none')
  await issuer.evaluate(async element => { await Promise.all(element.getAnimations().map(animation => animation.finished.catch(() => {}))) })
  const activeBorder = await issuer.evaluate(element => getComputedStyle(element).borderColor)
  await windowActivation(page, false)
  await expect(issuer).toHaveCSS('box-shadow', 'none')
  await expect(issuer).not.toHaveCSS('border-color', activeBorder)
  await expect(issuer).toHaveValue('Focus fixture')
  await expect(issuer).toBeFocused()
  expect(await issuer.evaluate((element: HTMLInputElement) => [element.selectionStart, element.selectionEnd])).toEqual([2, 5])
  await windowActivation(page, true)
  await expect(issuer).not.toHaveCSS('box-shadow', 'none')
  await expect(issuer).toHaveCSS('border-color', activeBorder)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: '外观与背景', exact: true }).click()
  const selectedTheme = page.getByRole('radio', { name: '二次元主题', exact: true })
  await selectedTheme.click()
  const selectionShadow = await selectedTheme.evaluate(element => getComputedStyle(element).boxShadow)
  await windowActivation(page, false)
  await expect(selectedTheme).toHaveAttribute('aria-checked', 'true')
  await expect(selectedTheme).toHaveCSS('box-shadow', selectionShadow)
  await expect(selectedTheme).toHaveCSS('outline-style', 'none')
  await windowActivation(page, true)
  await expect(selectedTheme).toHaveCSS('outline-style', 'none')
})

test('search outline follows activation and an input event recovers a window initially hidden', async ({ page }) => {
  await page.goto('/?demo')
  await page.getByRole('button', { name: '搜索', exact: true }).click()
  const search = page.getByRole('textbox', { name: '搜索令牌', exact: true })
  await search.fill('GitHub')
  const box = page.locator('.search-box')
  await box.evaluate(async element => { await Promise.all(element.getAnimations().map(animation => animation.finished.catch(() => {}))) })
  const activeBorder = await box.evaluate(element => getComputedStyle(element).borderColor)
  await windowActivation(page, false)
  await expect(box).not.toHaveCSS('border-color', activeBorder)
  await expect(search).toHaveValue('GitHub')
  await search.press('End')
  await expect(page.locator('html')).toHaveAttribute('data-window-active', 'true')
  await expect(box).toHaveCSS('border-color', activeBorder)
  await page.evaluate(() => {
    Object.defineProperty(document, 'hidden', { value: true, configurable: true })
    document.dispatchEvent(new Event('visibilitychange'))
  })
  await expect(page.locator('html')).toHaveAttribute('data-window-active', 'false')
  await expect(box).not.toHaveCSS('border-color', activeBorder)
  await page.evaluate(() => {
    delete (document as Partial<Document>).hidden
    window.dispatchEvent(new FocusEvent('focus'))
  })
  await expect(page.locator('html')).toHaveAttribute('data-window-active', 'true')
  await expect(search).toBeFocused()
  await expect(search).toHaveValue('GitHub')
})
