// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {vault} from '../models';
import {main} from '../models';

export function AddToken(arg1:vault.TokenInput):Promise<vault.Token>;

export function CheckForUpdates():Promise<main.UpdateStatus>;

export function CloseWindow():Promise<void>;

export function CopyAccount(arg1:string):Promise<void>;

export function CopyCode(arg1:string):Promise<void>;

export function DeleteToken(arg1:string):Promise<void>;

export function DownloadUpdate():Promise<main.UpdateStatus>;

export function GetState():Promise<main.State>;

export function GetTokens():Promise<Array<vault.Token>>;

export function GetUpdateStatus():Promise<main.UpdateStatus>;

export function ImportTokens(arg1:Array<string>):Promise<Array<vault.Token>>;

export function InstallUpdate():Promise<void>;

export function OpenReleasePage():Promise<void>;

export function PickBackground():Promise<main.Settings>;

export function PreviewClipboard():Promise<Array<main.ImportPreview>>;

export function PreviewImage(arg1:string):Promise<Array<main.ImportPreview>>;

export function PreviewText(arg1:string):Promise<Array<main.ImportPreview>>;

export function QuitApp():Promise<void>;

export function SaveSession(arg1:main.SessionState):Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<main.Settings>;

export function ToggleFavorite(arg1:string):Promise<void>;

export function UpdateToken(arg1:string,arg2:vault.TokenInput):Promise<vault.Token>;
