// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToken(arg1) {
  return window['go']['main']['App']['AddToken'](arg1);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function CopyAccount(arg1) {
  return window['go']['main']['App']['CopyAccount'](arg1);
}

export function CopyCode(arg1) {
  return window['go']['main']['App']['CopyCode'](arg1);
}

export function DeleteToken(arg1) {
  return window['go']['main']['App']['DeleteToken'](arg1);
}

export function DownloadUpdate() {
  return window['go']['main']['App']['DownloadUpdate']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetTokens() {
  return window['go']['main']['App']['GetTokens']();
}

export function GetUpdateStatus() {
  return window['go']['main']['App']['GetUpdateStatus']();
}

export function ImportTokens(arg1) {
  return window['go']['main']['App']['ImportTokens'](arg1);
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function OpenReleasePage() {
  return window['go']['main']['App']['OpenReleasePage']();
}

export function PickBackground() {
  return window['go']['main']['App']['PickBackground']();
}

export function PreviewClipboard() {
  return window['go']['main']['App']['PreviewClipboard']();
}

export function PreviewImage(arg1) {
  return window['go']['main']['App']['PreviewImage'](arg1);
}

export function PreviewText(arg1) {
  return window['go']['main']['App']['PreviewText'](arg1);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SaveSession(arg1) {
  return window['go']['main']['App']['SaveSession'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}

export function UpdateToken(arg1, arg2) {
  return window['go']['main']['App']['UpdateToken'](arg1, arg2);
}
